services:
  nginx:
    image: nginx:latest
    container_name: emotion_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx config
    #   - ./EmotionFrontend/dist/browser:/usr/share/nginx/html
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - frontend
      - backend
      - form
    networks:
      - app-network
    restart: always

  frontend:
    build: ./EmotionFrontend
    container_name: emotion_frontend
    expose:
      - "80"  # Map port 4200 to Nginx
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./EmotionBackend
    container_name: emotion_backend
    environment:
      - MONGO_URI = mongodb+srv://liangluya:liangluya@cluster0.awhbvnl.mongodb.net/Emotion?retryWrites=true&w=majority
    expose:
      - "3000"
    depends_on:
      - mongo
    networks:
      - app-network

  form:
    build: ./ReportEmotionForm
    container_name: emotion_form
    expose:
      - "80"  # Map port 80 to Nginx
    # ports:
    #   - "60312:80"
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # MongoDB default port
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:  # Persistent storage for MongoDB

networks:
  app-network:
    driver: bridge
